### ISSUE TITLE
In some cases, the GO API does not return expected result wrt GO-CAMs

### ISSUE THREAD

**Issue by kltm** [geneontology/go-fastapi#87]
I'm trying to understand why https://api.geneontology.org/api/gp/SGD:S000003407/models?causalmf=2 returns no values, when I can see 61f34dd300001044.json/61f34dd300001044.ttl, etc. do seem to have this identifier?

My guess is some kind of CURIE disconnect, but I wanted to check with @sierra-moxon to see if anything comes to mind beofer digging in more.

(My initial guess was a date/sync with release gap, but this seems to be a well-established model.)

**Comment by kltm** [comment]
Tagging @thomaspd

**Comment by sierra-moxon** [comment]
It looks like we have a mismatch between the [URI stored in minerva for SGD](https://github.com/geneontology/minerva/blob/master/minerva-core/src/main/resources/go_context.jsonld#L46) `http`, and the one exposed in [db-xrefs.yaml](https://github.com/geneontology/go-site/blob/4308751da22fa048c4098278ecab91b34aae21f6/metadata/db-xrefs.yaml#L2376) `https`

GO-API expands `SGD:S000003407` to `https://identifiers.org/sgd/S000003407` using the `go.csv` context in prefixmaps.  `go.csv` context in prefixmaps is generated by pulling in the `rdf_uri_prefix` from the db-xrefs.yaml.  Since the URL generated from minerva in the model is `http://identifiers.org/sgd/S000003407` (note the `http` vs, `https`), no results are returned from the GO-API query.

This PR would fix it, but I am not sure the consequences of changing the db-xrefs.yaml.

**Comment by kltm** [comment]
I wanted to specifically tag @balhoff and @cmungall , who might have context about knock-on effects outside of the GO.

**Comment by balhoff** [comment]
The `http` version is also in the Biolink prefix map. If we change the namespace used by Minerva to include `https`, besides updating the Minerva prefix map, we would need to apply a SPARQL Update to modify all models that mention SGD identifiers.

**Comment by kltm** [comment]
@balhoff Right, I think the thinking here is that the `http` version should be the "real" one, as that's what we use elsewhere, but the `rdf_uri_prefix` is "wrong". This PR would revert to the `http`, allowing that change to propagate and allowing us to continue.

**Comment by balhoff** [comment]
@kltm that sounds good! I thought SGD was wanting the `https`.

**Comment by kltm** [comment]
@sierra-moxon Wow, that SGD model has much bigness--I imagine it might be easy to miss something in there. @balhoff , I don't suppose you can inuit anything that might be going wrong in there?

**Comment by sierra-moxon** [comment]
@kltm - is there someone who believes that this model should be returned for this query?  Do we need to better document the endpoint, the page its rendering other models on, or take some other action here?

**Comment by kltm** [comment]
@sierra-moxon, this originally came in from @thomaspd:

---
I’ve previously used a GO-CAM from Marc as an example, and I want to use it in the Alliance paper. But now it doesn’t show up either on the Alliance page or the AmiGO page for the yeast ERG1 gene. There are no GO-CAMs being retrieved for:

https://amigo.geneontology.org/amigo/gene_product/SGD:S000003407

The GO-CAM is http://noctua.geneontology.org/workbench/noctua-visual-pathway-editor/?model_id=gomodel%3A61f34dd300001044

Do you know what might be going on?
---
The answer is then likely: it used to be a "legit" model, but has been changed such that it no longer is and no longer shows up in displays.

**Comment by sierra-moxon** [comment]
I think this issue can be closed; please let me know if I closed incorrectly.
