### ISSUE TITLE
taxon:1 vs NCBITaxon:1 for goid response from ontology/term/ endpoint

### ISSUE THREAD

**Issue by tmushayahama** [geneontology/go-fastapi#95]
The API endpoint https://api.geneontology.org/api/ontology/term/NCBITaxon:1 returns _**id: taxon:1**_ instead of _**NCBITaxon:1**_

```json
    {
       "goid":"taxon:1",
       "label":"root",
       ...
    }
```

However plugging **taxon:1** as a closure to GOlr doesn't seem to work, but **NCBITaxon:1** works

cc @sierra-moxon @kltm @vanaukenk

**Comment by cmungall** [comment]
It should be `NCBITaxon:1`

And to point out the obvious: it's not a GO ID. It's too late to fix this now I assume

**Comment by vanaukenk** [comment]
Noting from the 2024-06-13 workbenches call, that it's possible that other applications are expecting the existing value.
We'll want to check on this before putting a fix in.

**Comment by kltm** [comment]
Also, as this has been there a while, it might be good to see if any of our widgets, etc., already code to this "bug".

**Comment by sierra-moxon** [comment]
debugging results:

- https://raw.githubusercontent.com/geneontology/go-site/master/metadata/db-xrefs.yaml uses `taxon` as the prefix for NCBITaxon identifiers.  linkml/prefixmaps uses this file to make the prefixmap/context for the API.  Then, the API uses the resulting context to do URI compression when returning results from our RDF endpoint (the RDF return for the 'id' being queried is in URI format).  

- The API is returning as a `goid` from the API endpoint because the data structure of the return is hard coded as "goid."  
Which ontologies should a user querying this endpoint (noting that its getting data from the RDF endpoint) be able to query?  (@kltm @tmushayahama)

**Comment by cmungall** [comment]
> should the db-xrefs.yaml 'database' parameter for NCBITaxon change from taxon to NCBITaxon?

I think this is a good idea. We should also include a comment field indicating that `taxon:` is used in some file formats like GAF for legacy reasons.

**Comment by sierra-moxon** [comment]
Per discussion in developers' Slack, we will not change the hard coding of this endpoint to reflect its ability to search and return non-GO ontology identifiers. 

The other half of this ticket is fixed in geneontology/go-site, but also has the potential to break other things. 

So for now, this ticket won't be fixed.
